### PR TITLE
feat: add age of command not found index metric

### PR DESCRIPTION
**Pull request by andersson1234**
Monitors the age of the command not found index for each release.

### CODE REVIEW

**Comment by andersson1234** [comment]
Hey @seb128 , I'm having an issue with a conflicting error between flake8 and black. Black wants to format a bit of code like this:
```
                        date_str = line[
                            line.find('<td align="right">')
                            + len('<td align="right">') :
                        ]
```
And flake8 wants it formatted without the whitespace:
```
                        date_str = line[
                            line.find('<td align="right">')
                            + len('<td align="right">'):
                        ]
```
Without the whitespace. Not sure how to resolve this

**Comment by andersson1234** [comment]
Hi, this has passed all CI checks, please could you review @seb128

**Comment by andersson1234** [comment]
Or at least, it passed checks beforehand, I haven't changed anything I just rebase so it's weird it failed.

**Comment by andersson1234** [comment]
> Or at least, it passed checks beforehand, I haven't changed anything I just rebase so it's weird it failed.

Well, I mean the linter passed which is what I was having issues with, but the builds are having issues. Maybe a temporary failure?

**Review by murraybd — APPROVED** [review]

**Pull request merged**
