### PR TITLE
Report the count of the different sponsoring categories

### PR DESCRIPTION
**Pull request by seb128**
Now that the reports in a subdir we can list them with a bit of hackish parsing

### CODE REVIEW

**Comment by seb128** [comment]
I've added another commit which includes the age of the oldest item in the queue as well as the average

**Comment by iainlane** [comment]
Thanks. I've not reviewed yet, but just a quick comment on the parsing of the HTML listing... two things come to mind which could be done to avoid that.

  * Have all the information in one json file at a known location, with the team as a field in there on each entry
  * Write an index file to the output directory that you can read instead of needing to scrape

Not required now, but maybe something to consider.

**Comment by seb128** [comment]
I've reworked the script to just read the agregated report and use the sets defined there. It's not strictly the same but should be close enough

one example of the difference for the record
http://reqorts.qa.ubuntu.com/reports/sponsoring/jsons/xubuntu-uploaders.json

the report includes a flatpak entry which is flagged as 'security' set so isn't going to counted for 'xubuntu' now (but it might be right anyway if that's a security upload)

**Comment by iainlane** [comment]
Thanks! I like it. I think the security case is right too, nobody else can upload that stuff.If you wanted to do by uploader then that could be added to the same json too and added here later. (Slight worry that the `report` tag name should be called `packageset` or something if we're going to do that, but could probably figure out how to fix that later.)

**Pull request merged**
